version: "3"

services:
  # portfolio-site:
  # restart: always
  # build:
  # dockerfile: Dockerfile
  # networks:
  # - claes-work
  strapi:
    image: strapi/strapi
    volumes:
      - vstrapi:/srv/app
    ports:
      - "188.68.62.174:1337:1337"

networks:
  claes-work:
    external: true

volumes:
  vstrapi:
